### ISSUE TITLE
Error when running MATLAB evaluation script

### ISSUE THREAD

**Issue by jpsml** [cvlab-epfl/MVAug#1]
I am trying to run the MATLAB evaluation script, but I am getting the error below:

(mvaug) D:\MVAug>python misc/matlabeval/evaluate.py model_736
Error using evaluateDetection
Too many input arguments.

Traceback (most recent call last):
  File "misc/matlabeval/evaluate.py", line 55, in <module>
    recall, precision, moda, modp = evaluate(res_fpath, gt_fpath, 'Wildtrack', args.metric_threshold, eng)
  File "misc/matlabeval/evaluate.py", line 17, in evaluate
    res = eng.evaluateDetection(res_fpath, gt_fpath, dataset, metric_threshold)
  File "C:\Users\mhmon\.conda\envs\mvaug\lib\site-packages\matlab\engine\matlabengine.py", line 71, in __call__
    _stderr, feval=True).result()
  File "C:\Users\mhmon\.conda\envs\mvaug\lib\site-packages\matlab\engine\futureresult.py", line 67, in result
    return self.__future.result(timeout)
  File "C:\Users\mhmon\.conda\envs\mvaug\lib\site-packages\matlab\engine\fevalfuture.py", line 82, in result
    self._result = pythonengine.getFEvalResult(self._future,self._nargout, None, out=self._out, err=self._err)
matlab.engine.MatlabExecutionError: Too many input arguments.

My MATLAB version is R2018a. Do you know how to solve this problem? Best regards.

**Comment by jpsml** [comment]
I have fixed it by making the following changes to evaluateDetection.m from motchallenge-devkit:

Line 1:
function detResults=evaluateDetection(res_fpath,gt_fpath, chlname, metric_threshold)

Line 108:
options.eval3d=0;
options.td=metric_threshold;
[detMetsAll, detMetsInfo, detMetsAddInfo]=CLEAR_MOD_HUN(gtAllMatrix,detAllMatrix,options);
